name: CI-CD

on:
  push:

jobs:
  test:
    runs-on: self-hosted
    env:
      URLBDD: ${{ secrets.URLBDD }}
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: python -m pip install -r requirements.txt

      - name: Lancer les tests
        run: python -m pytest

  deploy:
    needs: test
    runs-on: self-hosted
    timeout-minutes: 720
    concurrency:
      group: uvicorn
      cancel-in-progress: true
    env:
      URLBDD: ${{ secrets.URLBDD }}
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: python -m pip install -r requirements.txt

      - name: Lancer l'API
        run: python -m uvicorn main:app --host 127.0.0.1 --port 8000
